name: Deploy SQL Scripts to RDS

on:
  push:
    branches:
      - main  # Rodar o pipeline quando houver push no branch main

jobs:
  deploy-sql:
    name: Deploy SQL Scripts
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # Instalação do cliente PostgreSQL
      - name: Instalar cliente PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      # Rodar scripts SQL
      - name: Executar Scripts SQL no RDS
        env:
          DB_HOST: ${{ secrets.DB_HOST }}     # Endpoint do banco de dados
          DB_NAME: ${{ secrets.DB_NAME }}     # Nome do banco de dados
          DB_USER: ${{ secrets.DB_USER }}     # Usuário do banco de dados
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }} # Senha do banco de dados
        run: |
          for script in $(ls scripts/*.sql | sort); do
            echo "Executando $script..."
            PGPASSWORD=${DB_PASSWORD} psql \
              --host=${DB_HOST} \
              --port=5432 \
              --username=${DB_USER} \
              --dbname=${DB_NAME} \
              --file=$script
          done